version: "3"

services:
  redis-server:
    image: "redis"
    ports:
      - "${REDIS_PORT}:${REDIS_PORT}"
    expose:
      - "${REDIS_PORT}"

  roga-teste-postgres-compose:
    image: postgres
    env_file:
      - .env

    environment:
      POSTGRES_PASSWORD: "${DB_PASSWORD}"
      POSTGRES_USER: "${DB_USERNAME}"
      POSTGRES_DB: "${DB}"

    volumes:
      - "${DB_VOLUME}"
    ports:
      - "${DB_PORT}:${DB_PORT}"
